### ISSUE TITLE
Could you release full checkpoints?

### ISSUE THREAD

**Issue by Monalissaa** [XinyiYing/MoCoPnet#3]
Hi, thanks again for your excellent works.
Is it possible to release the full checkpoints of the model, so we can make a comparison or finetune it? Thanks.

**Comment by Monalissaa** [comment]
😿

**Comment by Monalissaa** [comment]
I'm sorry I didn't see it in the ‘log’ folder, I didn't expect the network to be so small, thank you for your wonderful work!

**Comment by XinyiYing** [comment]
the full checkpoints [MoCoPnet.pth.tar] has been released in (https://github.com/XinyiYing/MoCoPnet/blob/main/code/log/MoCoPnet.pth.tar)
